# Generated by Django 5.2.8 on 2025-12-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmastermaster', '0003_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticketmaster_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
